version: '3.9'
services:
  postgress:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=usr
      - POSTGRESS_PASSWORD=admin

